// <auto-generated />
using AcunmedyaLisesi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AcunmedyaLisesi.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240703201258_ContextOlusturma")]
    partial class ContextOlusturma
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AcunmedyaLisesi.Web.Models.Bilisim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EgitimciId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("int");

                    b.Property<int>("SınavId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Bilisims");
                });

            modelBuilder.Entity("AcunmedyaLisesi.Web.Models.Egitimciler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BilisimId")
                        .HasColumnType("int");

                    b.Property<int>("FenId")
                        .HasColumnType("int");

                    b.Property<int>("MatematikId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BilisimId");

                    b.HasIndex("FenId");

                    b.HasIndex("MatematikId");

                    b.ToTable("Egitimcies");
                });

            modelBuilder.Entity("AcunmedyaLisesi.Web.Models.Fen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EgitimciId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("int");

                    b.Property<int>("SınavId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Fens");
                });

            modelBuilder.Entity("AcunmedyaLisesi.Web.Models.Matematik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EgitimciId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("int");

                    b.Property<int>("SınavId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Matematiks");
                });

            modelBuilder.Entity("AcunmedyaLisesi.Web.Models.Ogrenciler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BilisimId")
                        .HasColumnType("int");

                    b.Property<int>("EgitimciId")
                        .HasColumnType("int");

                    b.Property<int>("EgitimcilerId")
                        .HasColumnType("int");

                    b.Property<int>("FenId")
                        .HasColumnType("int");

                    b.Property<int>("MatematikId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SınavId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BilisimId");

                    b.HasIndex("EgitimcilerId");

                    b.HasIndex("FenId");

                    b.HasIndex("MatematikId");

                    b.ToTable("Ogrencies");
                });

            modelBuilder.Entity("AcunmedyaLisesi.Web.Models.Sınavlar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BilisimId")
                        .HasColumnType("int");

                    b.Property<int>("FenId")
                        .HasColumnType("int");

                    b.Property<int>("MatematikId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sınavlars");
                });

            modelBuilder.Entity("BilisimSınavlar", b =>
                {
                    b.Property<int>("BilisimId")
                        .HasColumnType("int");

                    b.Property<int>("SınavlarsId")
                        .HasColumnType("int");

                    b.HasKey("BilisimId", "SınavlarsId");

                    b.HasIndex("SınavlarsId");

                    b.ToTable("BilisimSınavlar");
                });

            modelBuilder.Entity("FenSınavlar", b =>
                {
                    b.Property<int>("FenId")
                        .HasColumnType("int");

                    b.Property<int>("SınavlarsId")
                        .HasColumnType("int");

                    b.HasKey("FenId", "SınavlarsId");

                    b.HasIndex("SınavlarsId");

                    b.ToTable("FenSınavlar");
                });

            modelBuilder.Entity("MatematikSınavlar", b =>
                {
                    b.Property<int>("MatematikId")
                        .HasColumnType("int");

                    b.Property<int>("SınavlarsId")
                        .HasColumnType("int");

                    b.HasKey("MatematikId", "SınavlarsId");

                    b.HasIndex("SınavlarsId");

                    b.ToTable("MatematikSınavlar");
                });

            modelBuilder.Entity("OgrencilerSınavlar", b =>
                {
                    b.Property<int>("OgrencilersId")
                        .HasColumnType("int");

                    b.Property<int>("SınavlarId")
                        .HasColumnType("int");

                    b.HasKey("OgrencilersId", "SınavlarId");

                    b.HasIndex("SınavlarId");

                    b.ToTable("OgrencilerSınavlar");
                });

            modelBuilder.Entity("AcunmedyaLisesi.Web.Models.Egitimciler", b =>
                {
                    b.HasOne("AcunmedyaLisesi.Web.Models.Bilisim", "Bilisim")
                        .WithMany("Egitimciler")
                        .HasForeignKey("BilisimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcunmedyaLisesi.Web.Models.Fen", "Fen")
                        .WithMany("Egitimciler")
                        .HasForeignKey("FenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcunmedyaLisesi.Web.Models.Matematik", "Matematik")
                        .WithMany("Egitimciler")
                        .HasForeignKey("MatematikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bilisim");

                    b.Navigation("Fen");

                    b.Navigation("Matematik");
                });

            modelBuilder.Entity("AcunmedyaLisesi.Web.Models.Ogrenciler", b =>
                {
                    b.HasOne("AcunmedyaLisesi.Web.Models.Bilisim", "Bilisim")
                        .WithMany("Ogrenciler")
                        .HasForeignKey("BilisimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcunmedyaLisesi.Web.Models.Egitimciler", "Egitimciler")
                        .WithMany()
                        .HasForeignKey("EgitimcilerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcunmedyaLisesi.Web.Models.Fen", "Fen")
                        .WithMany("Ogrenciler")
                        .HasForeignKey("FenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcunmedyaLisesi.Web.Models.Matematik", "Matematik")
                        .WithMany("Ogrenciler")
                        .HasForeignKey("MatematikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bilisim");

                    b.Navigation("Egitimciler");

                    b.Navigation("Fen");

                    b.Navigation("Matematik");
                });

            modelBuilder.Entity("BilisimSınavlar", b =>
                {
                    b.HasOne("AcunmedyaLisesi.Web.Models.Bilisim", null)
                        .WithMany()
                        .HasForeignKey("BilisimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcunmedyaLisesi.Web.Models.Sınavlar", null)
                        .WithMany()
                        .HasForeignKey("SınavlarsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FenSınavlar", b =>
                {
                    b.HasOne("AcunmedyaLisesi.Web.Models.Fen", null)
                        .WithMany()
                        .HasForeignKey("FenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcunmedyaLisesi.Web.Models.Sınavlar", null)
                        .WithMany()
                        .HasForeignKey("SınavlarsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MatematikSınavlar", b =>
                {
                    b.HasOne("AcunmedyaLisesi.Web.Models.Matematik", null)
                        .WithMany()
                        .HasForeignKey("MatematikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcunmedyaLisesi.Web.Models.Sınavlar", null)
                        .WithMany()
                        .HasForeignKey("SınavlarsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OgrencilerSınavlar", b =>
                {
                    b.HasOne("AcunmedyaLisesi.Web.Models.Ogrenciler", null)
                        .WithMany()
                        .HasForeignKey("OgrencilersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AcunmedyaLisesi.Web.Models.Sınavlar", null)
                        .WithMany()
                        .HasForeignKey("SınavlarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AcunmedyaLisesi.Web.Models.Bilisim", b =>
                {
                    b.Navigation("Egitimciler");

                    b.Navigation("Ogrenciler");
                });

            modelBuilder.Entity("AcunmedyaLisesi.Web.Models.Fen", b =>
                {
                    b.Navigation("Egitimciler");

                    b.Navigation("Ogrenciler");
                });

            modelBuilder.Entity("AcunmedyaLisesi.Web.Models.Matematik", b =>
                {
                    b.Navigation("Egitimciler");

                    b.Navigation("Ogrenciler");
                });
#pragma warning restore 612, 618
        }
    }
}
